// <auto-generated />
namespace WooxTravel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_email_column_removed_on_reservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_email_column_removed_on_reservation));
        
        string IMigrationMetadata.Id
        {
            get { return "202410081831407_mig_email_column_removed_on_reservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
