// <auto-generated />
namespace WooxTravel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class pricecolumnconvertedtoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pricecolumnconvertedtoint));
        
        string IMigrationMetadata.Id
        {
            get { return "202411042023156_price-column-converted-to-int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
