// <auto-generated />
namespace WooxTravel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_category_status_changed_to_boolean : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_category_status_changed_to_boolean));
        
        string IMigrationMetadata.Id
        {
            get { return "202410131927075_mig_category_status_changed_to_boolean"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
