// <auto-generated />
namespace WooxTravel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class capacity_column_added_on_destination_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(capacity_column_added_on_destination_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202410221732590_capacity_column_added_on_destination_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
