// <auto-generated />
namespace WooxTravel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_admin_table_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_admin_table_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202410131956593_mig_admin_table_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
